/*
    knife.h
    Generated by FMOD Designer v1.7.23 
*/

#ifndef KNIFE_H
#define KNIFE_H

/*
    Total number of events in the project
*/
const int EVENTCOUNT_KNIFE = 2;

/*
    EventGroup/Event-relative indices
*/
const int EVENTGROUP_KNIFE_KNIFE = 0;
const int EVENTGROUPCOUNT_KNIFE_KNIFE = 2;
const int EVENT_KNIFE_KNIFE_MELEE = 0;
const int EVENT_KNIFE_KNIFE_COLLIDE = 1;

/*
    Project-unique event ids
*/
const int EVENTID_KNIFE_KNIFE_MELEE = 0;
const int EVENTID_KNIFE_KNIFE_COLLIDE = 1;

const int EVENTCATEGORY_KNIFE_MASTER = 0;
const int EVENTCATEGORYCOUNT_KNIFE_MASTER = 2;

const int EVENTCATEGORY_KNIFE_MASTER_MUSIC = 0;
const int EVENTCATEGORYCOUNT_KNIFE_MASTER_MUSIC = 0;

#endif /* KNIFE_H */
